# Generated by Django 2.0 on 2018-08-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20180810_1806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'artist')},
        ),
    ]
