# Generated by Django 2.0 on 2018-08-18 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0004_song_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-listeners_fm']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-listeners_fm']},
        ),
    ]
