# Generated by Django 2.0 on 2018-09-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20180818_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(blank=True, related_name='playlist', to='music.Song'),
        ),
    ]
