# Generated by Django 2.0 on 2018-09-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20180912_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenersong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener', to='music.Song'),
        ),
    ]
