# Generated by Django 2.0 on 2018-09-13 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0008_auto_20180913_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenersong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
