# Generated by Django 2.0 on 2018-09-14 10:54

from django.db import migrations, models

import music.validations


class Migration(migrations.Migration):
    dependencies = [
        ('music', '0009_auto_20180913_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[music.validations.validate_length]),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=100, validators=[music.validations.validate_length]),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100, validators=[music.validations.validate_length]),
        ),
    ]
