# Generated by Django 2.0 on 2018-09-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20180914_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(default=None, max_length=35, null=True, unique=True),
        ),
    ]
