# Generated by Django 2.0 on 2018-10-07 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0015_auto_20180924_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorite',
            field=models.ManyToManyField(related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
