# Generated by Django 2.0 on 2018-10-17 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_song_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
