# Generated by Django 2.0 on 2018-10-21 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20181017_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarartist',
            name='first_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='similarartist',
            name='second_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar', to='music.Artist'),
        ),
    ]
