# Generated by Django 2.0.8 on 2018-11-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20181021_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='time',
        ),
    ]
