# Generated by Django 2.0.8 on 2018-12-11 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0020_auto_20181129_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listenersong',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='listenersong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_listener', to='music.Song'),
        ),
        migrations.AlterField(
            model_name='listenersong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_listener', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
