# Generated by Django 2.0.8 on 2018-12-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20181211_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
