# Generated by Django 2.0.8 on 2019-03-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_auto_20190301_2051'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='artist',
            name='music_artis_id_a6462a_idx',
        ),
    ]
