# Generated by Django 2.0.8 on 2019-03-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20190301_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
    ]
