# Generated by Django 2.0.8 on 2018-12-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181212_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='slug',
        ),
    ]
