# Generated by Django 2.0.8 on 2019-01-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_socialnetwork_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='name',
        ),
    ]
