# Generated by Django 2.0 on 2018-08-04 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_artist_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='similarartist',
            unique_together={('first_artist', 'second_artist')},
        ),
    ]
