# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180414_2051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([]),
        ),
    ]
