# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import storage.image_storage


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180415_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, max_length=500, null=True, storage=storage.image_storage.ImageStorage(), upload_to=b''),
        ),
    ]
